(() => {
  const ds=window.DataService, cfg=window.APP_CONFIG;
  const loginView=document.getElementById("loginView"), dashboard=document.getElementById("dashboardView");
  let points=[], map=null, marker=null, editing=null;
  const labels={hydrant:"Κρουνός",tank:"Δεξαμενή",water_source:"Υδροληψία"};
  const cond={available:"Λειτουργικό",unknown:"Άγνωστη",unavailable:"Εκτός λειτουργίας"};

  function msg(id,text,error=false){const e=document.getElementById(id);e.textContent=text;e.classList.toggle("error",error);}
  function showDashboard(){loginView.classList.add("hidden");dashboard.classList.remove("hidden");loadPoints();}
  function showLogin(){dashboard.classList.add("hidden");loginView.classList.remove("hidden");}

  document.getElementById("loginForm").addEventListener("submit",async e=>{e.preventDefault(); if(!ds.configured)return msg("loginMessage","Συμπλήρωσε πρώτα supabaseUrl και supabaseAnonKey στο js/config.js",true); msg("loginMessage","Σύνδεση…"); const {error}=await ds.client.auth.signInWithPassword({email:document.getElementById("loginEmail").value.trim(),password:document.getElementById("loginPassword").value}); if(error)return msg("loginMessage",error.message,true);showDashboard();});
  document.getElementById("logoutButton").addEventListener("click",async()=>{await ds.client.auth.signOut();showLogin();});

  async function boot(){if(!ds.configured)return; const {data}=await ds.client.auth.getSession(); if(data.session)showDashboard();}
  async function loadPoints(){try{points=await ds.allPoints();renderAll();}catch(e){alert(e.message);}}
  function renderAll(){renderStats();renderTable();renderRecent();}
  function renderStats(){document.getElementById("statTotal").textContent=points.length;document.getElementById("statHydrants").textContent=points.filter(p=>p.category==="hydrant").length;document.getElementById("statTanks").textContent=points.filter(p=>p.category==="tank").length;document.getElementById("statSources").textContent=points.filter(p=>p.category==="water_source").length; const x={available:0,unknown:0,unavailable:0};points.forEach(p=>x[p.condition]++);document.getElementById("conditionSummary").innerHTML=Object.entries(x).map(([k,v])=>`<div><span>${cond[k]}</span><strong>${v}</strong></div>`).join("");}
  function renderRecent(){document.getElementById("recentPoints").innerHTML=points.slice(0,6).map(p=>`<button type="button" data-edit="${p.id}"><span><strong>${esc(p.name)}</strong><small>${labels[p.category]}</small></span><b>›</b></button>`).join("")||"<p>Δεν υπάρχουν σημεία.</p>";document.querySelectorAll("[data-edit]").forEach(b=>b.addEventListener("click",()=>editPoint(b.dataset.edit)));}
  function filtered(){const q=document.getElementById("adminSearch").value.trim().toLocaleLowerCase("el"),c=document.getElementById("adminCategory").value;return points.filter(p=>(!q||p.name.toLocaleLowerCase("el").includes(q))&&(!c||p.category===c));}
  function renderTable(){document.getElementById("pointsTableBody").innerHTML=filtered().map(p=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${labels[p.category]}</td><td><span class="table-status ${p.condition}">${cond[p.condition]}</span></td><td>${p.publication_status}</td><td class="row-actions"><button data-edit="${p.id}" title="Επεξεργασία">✏️</button><button data-delete="${p.id}" title="Διαγραφή">🗑️</button></td></tr>`).join("")||`<tr><td colspan="5">Δεν βρέθηκαν σημεία.</td></tr>`;document.querySelectorAll("[data-edit]").forEach(b=>b.addEventListener("click",()=>editPoint(b.dataset.edit)));document.querySelectorAll("[data-delete]").forEach(b=>b.addEventListener("click",()=>removePoint(b.dataset.delete)));}
  document.getElementById("adminSearch").addEventListener("input",renderTable);document.getElementById("adminCategory").addEventListener("change",renderTable);

  const viewMeta={overview:["Επισκόπηση","Συνολική εικόνα των σημείων νερού"],points:["Σημεία","Αναζήτηση και διαχείριση"],editor:["Νέο σημείο","Καταχώρηση ή επεξεργασία"]};
  function setView(name){document.querySelectorAll(".dashboard-section").forEach(s=>s.classList.add("hidden"));document.getElementById(name+"View").classList.remove("hidden");document.querySelectorAll(".nav-item[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===name));document.getElementById("viewTitle").textContent=viewMeta[name][0];document.getElementById("viewSubtitle").textContent=viewMeta[name][1];if(name==="editor")setTimeout(()=>map?.invalidateSize(),80);}
  document.querySelectorAll(".nav-item[data-view]").forEach(b=>b.addEventListener("click",()=>setView(b.dataset.view)));document.getElementById("newPointButton").addEventListener("click",()=>{resetForm();setView("editor");});

  function ensureMap(){if(map)return;map=L.map("adminMap").setView(cfg.initialCenter,cfg.initialZoom);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap"}).addTo(map);map.on("click",e=>setCoords(e.latlng.lat,e.latlng.lng));}
  function setCoords(lat,lng){document.getElementById("pointLatitude").value=lat.toFixed(7);document.getElementById("pointLongitude").value=lng.toFixed(7);if(marker)marker.setLatLng([lat,lng]);else marker=L.marker([lat,lng],{draggable:true}).addTo(map).on("dragend",()=>{const p=marker.getLatLng();setCoords(p.lat,p.lng);});}
  function resetForm(){editing=null;document.getElementById("pointForm").reset();document.getElementById("pointId").value="";document.getElementById("formTitle").textContent="Νέο σημείο";ensureMap();if(marker){map.removeLayer(marker);marker=null;}map.setView(cfg.initialCenter,cfg.initialZoom);msg("formMessage","");}
  function editPoint(id){const p=points.find(x=>x.id===id);if(!p)return;editing=p;setView("editor");ensureMap();document.getElementById("formTitle").textContent="Επεξεργασία σημείου";document.getElementById("pointId").value=p.id;document.getElementById("pointName").value=p.name;document.getElementById("pointCategory").value=p.category;document.getElementById("pointCondition").value=p.condition;document.getElementById("pointPublication").value=p.publication_status;document.getElementById("pointLastChecked").value=p.last_checked_at||"";document.getElementById("pointNotes").value=p.notes||"";setCoords(p.latitude,p.longitude);map.setView([p.latitude,p.longitude],17);}
  document.getElementById("pointForm").addEventListener("submit",async e=>{e.preventDefault();const p={id:document.getElementById("pointId").value||null,name:document.getElementById("pointName").value,category:document.getElementById("pointCategory").value,condition:document.getElementById("pointCondition").value,publication_status:document.getElementById("pointPublication").value,last_checked_at:document.getElementById("pointLastChecked").value,latitude:document.getElementById("pointLatitude").value,longitude:document.getElementById("pointLongitude").value,notes:document.getElementById("pointNotes").value};msg("formMessage","Αποθήκευση…");try{await ds.savePoint(p);msg("formMessage","Το σημείο αποθηκεύτηκε.");await loadPoints();setTimeout(()=>setView("points"),500);}catch(err){msg("formMessage",err.message,true);}});
  document.getElementById("cancelEditButton").addEventListener("click",()=>setView("points"));document.getElementById("useGpsButton").addEventListener("click",()=>{if(!navigator.geolocation)return msg("formMessage","Δεν υποστηρίζεται GPS",true);navigator.geolocation.getCurrentPosition(p=>{ensureMap();setCoords(p.coords.latitude,p.coords.longitude);map.setView([p.coords.latitude,p.coords.longitude],17);},()=>msg("formMessage","Δεν ήταν δυνατός ο εντοπισμός",true),{enableHighAccuracy:true,timeout:15000});});
  async function removePoint(id){const p=points.find(x=>x.id===id);if(!confirm(`Να διαγραφεί οριστικά το σημείο «${p?.name}»;`))return;try{await ds.deletePoint(id);await loadPoints();}catch(e){alert(e.message);}}
  function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
  ensureMap();boot();
})();
