(() => {
  "use strict";
  const navModal=document.getElementById("navigationModal"), compassModal=document.getElementById("compassModal");
  const targetText=document.getElementById("navigationTarget"), compassTarget=document.getElementById("compassTarget");
  const arrow=document.getElementById("compassArrow"), distanceEl=document.getElementById("compassDistance"), bearingEl=document.getElementById("compassBearing"), accuracyEl=document.getElementById("compassAccuracy");
  const permissionButton=document.getElementById("enableCompassPermission");
  let target=null,mapRef=null,getUser=null,toast=()=>{},watchId=null,heading=null,lastPosition=null,line=null,targetMarker=null;
  const rad=d=>d*Math.PI/180,deg=r=>r*180/Math.PI;
  function distance(lat1,lon1,lat2,lon2){const R=6371000,p1=rad(lat1),p2=rad(lat2),dp=rad(lat2-lat1),dl=rad(lon2-lon1),a=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
  function bearing(lat1,lon1,lat2,lon2){const y=Math.sin(rad(lon2-lon1))*Math.cos(rad(lat2)),x=Math.cos(rad(lat1))*Math.sin(rad(lat2))-Math.sin(rad(lat1))*Math.cos(rad(lat2))*Math.cos(rad(lon2-lon1));return (deg(Math.atan2(y,x))+360)%360;}
  function cardinal(b){return ["Β","ΒΑ","Α","ΝΑ","Ν","ΝΔ","Δ","ΒΔ"][Math.round(b/45)%8];}
  function fmt(m){return m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(m<10000?1:0)} km`;}
  function close(el){el.classList.add("hidden");document.body.classList.remove("modal-open");}
  function openModal(el){el.classList.remove("hidden");document.body.classList.add("modal-open");}
  function update(){if(!target||!lastPosition)return;const b=bearing(lastPosition.coords.latitude,lastPosition.coords.longitude,target.latitude,target.longitude),d=distance(lastPosition.coords.latitude,lastPosition.coords.longitude,target.latitude,target.longitude);const rotation=heading==null?b:(b-heading+360)%360;arrow.style.transform=`rotate(${rotation}deg)`;distanceEl.textContent=`${fmt(d)} μέχρι το σημείο`;bearingEl.textContent=`Κατεύθυνση ${cardinal(b)} · ${Math.round(b)}°`;accuracyEl.textContent=`Ακρίβεια GPS ±${Math.round(lastPosition.coords.accuracy||0)} m${heading==null?" · Η πυξίδα δεν είναι διαθέσιμη":""}`;}
  function onOrientation(e){let h=null;if(typeof e.webkitCompassHeading==="number")h=e.webkitCompassHeading;else if(e.absolute&&typeof e.alpha==="number")h=(360-e.alpha)%360;else if(typeof e.alpha==="number")h=(360-e.alpha)%360;if(h!=null){heading=h;update();}}
  async function enableOrientation(){try{if(typeof DeviceOrientationEvent!=="undefined"&&typeof DeviceOrientationEvent.requestPermission==="function"){const result=await DeviceOrientationEvent.requestPermission();if(result!=="granted")throw new Error("Δεν δόθηκε άδεια πυξίδας.");}window.addEventListener("deviceorientationabsolute",onOrientation,true);window.addEventListener("deviceorientation",onOrientation,true);permissionButton.classList.add("hidden");}catch(e){toast(e.message||"Δεν ενεργοποιήθηκε η πυξίδα.","error");}}
  function startCompass(){close(navModal);openModal(compassModal);compassTarget.textContent=target.name;heading=null;lastPosition=null;distanceEl.textContent="Αναμονή GPS…";bearingEl.textContent="";accuracyEl.textContent="";if(typeof DeviceOrientationEvent!=="undefined"&&typeof DeviceOrientationEvent.requestPermission==="function")permissionButton.classList.remove("hidden");else enableOrientation();if(!navigator.geolocation){toast("Η συσκευή δεν υποστηρίζει GPS.","error");return;}if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=navigator.geolocation.watchPosition(p=>{lastPosition=p;update();},e=>toast(({1:"Δεν δόθηκε άδεια GPS.",2:"Η θέση δεν είναι διαθέσιμη.",3:"Η λήψη GPS καθυστέρησε."})[e.code]||"Σφάλμα GPS.","error"),{enableHighAccuracy:true,maximumAge:0,timeout:25000});}
  function stopCompass(){if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;window.removeEventListener("deviceorientationabsolute",onOrientation,true);window.removeEventListener("deviceorientation",onOrientation,true);close(compassModal);}
  function nativeMaps(){const lat=target.latitude,lon=target.longitude,label=encodeURIComponent(target.name);const ios=/iPad|iPhone|iPod/.test(navigator.userAgent);location.href=ios?`maps://?daddr=${lat},${lon}&dirflg=d`:`geo:${lat},${lon}?q=${lat},${lon}(${label})`;}
  function googleMaps(){location.href=`https://www.google.com/maps/dir/?api=1&destination=${target.latitude},${target.longitude}&travelmode=driving`;}
  function centerMap(){const p=lastPosition?{lat:lastPosition.coords.latitude,lng:lastPosition.coords.longitude}:getUser?.();if(mapRef&&p){if(line)mapRef.removeLayer(line);if(targetMarker)mapRef.removeLayer(targetMarker);line=L.polyline([[p.lat,p.lng],[target.latitude,target.longitude]],{weight:5,dashArray:"9 8"}).addTo(mapRef);targetMarker=L.circleMarker([target.latitude,target.longitude],{radius:9,weight:3,fillOpacity:1}).addTo(mapRef);mapRef.fitBounds(line.getBounds(),{padding:[50,50],maxZoom:16});stopCompass();}}
  document.getElementById("closeNavigationModal").onclick=()=>close(navModal);document.getElementById("closeCompassModal").onclick=stopCompass;document.getElementById("startOfflineCompass").onclick=startCompass;document.getElementById("openNativeMaps").onclick=nativeMaps;document.getElementById("openGoogleMaps").onclick=googleMaps;document.getElementById("enableCompassPermission").onclick=enableOrientation;document.getElementById("centerNavigationMap").onclick=centerMap;
  window.FireWaterNavigation={open(opts){target=opts;mapRef=opts.map;getUser=opts.user;toast=opts.toast||toast;targetText.textContent=opts.name;openModal(navModal);}};
})();
