(() => {
  "use strict";
  const modal=document.getElementById("offlineSetupModal"),summary=document.getElementById("offlineDeviceSummary"),instructions=document.getElementById("offlineInstructions"),status=document.getElementById("offlineSetupStatus");
  const ios=/iPad|iPhone|iPod/.test(navigator.userAgent),android=/Android/.test(navigator.userAgent);const readyKey="fwm-offline-map-ready";
  function open(){render();modal.classList.remove("hidden");document.body.classList.add("modal-open");}
  function close(){modal.classList.add("hidden");document.body.classList.remove("modal-open");}
  function render(){const ready=localStorage.getItem(readyKey);summary.innerHTML=`<div><strong>Συσκευή</strong><span>${ios?"iPhone / iPad":android?"Android":"Άλλη συσκευή"}</span></div><div><strong>Σύνδεση</strong><span>${navigator.onLine?"Online":"Offline"}</span></div><div><strong>Offline χάρτης</strong><span class="${ready?"ready":"not-ready"}">${ready?`Δηλώθηκε έτοιμος · ${ready}`:"Δεν έχει επιβεβαιωθεί"}</span></div>`;instructions.innerHTML=ios?`<h3>Apple Maps</h3><ol><li>Πάτησε «Άνοιγμα χαρτών».</li><li>Στους Χάρτες πάτησε τη φωτογραφία ή τα αρχικά σου.</li><li>Επίλεξε «Χάρτες εκτός σύνδεσης» και «Λήψη νέου χάρτη».</li><li>Αναζήτησε Κόρινθο και μεγάλωσε την περιοχή ώστε να καλύπτει την Κορινθία.</li><li>Πάτησε «Λήψη».</li></ol>`:`<h3>Google Maps</h3><ol><li>Πάτησε «Άνοιγμα χαρτών».</li><li>Στο Google Maps πάτησε τη φωτογραφία σου.</li><li>Επίλεξε «Χάρτες εκτός σύνδεσης».</li><li>Πάτησε «Επιλέξτε τον δικό σας χάρτη».</li><li>Κάλυψε την Κορινθία και πάτησε «Λήψη».</li></ol>`;}
  function openMaps(){location.href=ios?"maps://?q=Κόρινθος":"geo:37.9386,22.9322?q=Κόρινθος";}
  function markReady(){const d=new Date().toLocaleDateString("el-GR");localStorage.setItem(readyKey,d);status.textContent="Η συσκευή σημειώθηκε ως έτοιμη. Κάνε και μία δοκιμή σε λειτουργία πτήσης.";status.className="offline-setup-status success";render();}
  function testGps(){status.textContent="Γίνεται λήψη νέου στίγματος…";status.className="offline-setup-status";navigator.geolocation?.getCurrentPosition(p=>{status.textContent=`GPS OK · ακρίβεια ±${Math.round(p.coords.accuracy||0)} m`;status.className="offline-setup-status success";},e=>{status.textContent=({1:"Δεν δόθηκε άδεια GPS.",2:"Δεν βρέθηκε θέση.",3:"Η λήψη GPS καθυστέρησε."})[e.code]||"Σφάλμα GPS.";status.className="offline-setup-status error";},{enableHighAccuracy:true,maximumAge:0,timeout:25000});}
  document.getElementById("offlineSetupButton").onclick=open;document.getElementById("closeOfflineSetup").onclick=close;document.getElementById("openMapsForSetup").onclick=openMaps;document.getElementById("markOfflineReady").onclick=markReady;document.getElementById("testGpsButton").onclick=testGps;
})();
