(() => {
  "use strict";
  const config=window.APP_CONFIG, dataService=window.DataService;
  const map=L.map("map",{zoomControl:false,preferCanvas:true}).setView(config.initialCenter,config.initialZoom);
  L.control.zoom({position:"bottomright"}).addTo(map);
  window.FireWaterMap = window.FireWaterMap || {};
  window.FireWaterMap.map = map;
  L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);
  const icons={hydrant:"icons/hydrant.svg",tank:"icons/tank.svg",water_source:"icons/water-source.svg"};
  const labels={hydrant:"Κρουνός",tank:"Δεξαμενή",water_source:"Σημείο υδροληψίας"};
  const conditions={available:"Λειτουργικό",unknown:"Άγνωστη κατάσταση",unavailable:"Εκτός λειτουργίας"};
  const state={points:[],markers:[],user:null,userMarker:null,accuracyCircle:null,radiusCircle:null,radiusKm:Number(config.defaultRadiusKm)||4,nearby:false,operation:false,watchId:null,follow:true};
  const toastEl=document.getElementById("toast"),sheet=document.getElementById("bottomSheet"),sheetContent=document.getElementById("sheetContent"),locateButton=document.getElementById("locateButton");let toastTimer;
  const organisationName=document.getElementById("organisationName");if(organisationName)organisationName.textContent=config.organisation;
  function toast(m,t="info"){clearTimeout(toastTimer);toastEl.textContent=m;toastEl.dataset.type=t;toastEl.classList.add("show");toastTimer=setTimeout(()=>toastEl.classList.remove("show"),3800);}
  function distanceKm(a,b,c,d){const R=6371,r=x=>x*Math.PI/180,dl=r(c-a),dn=r(d-b),q=Math.sin(dl/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dn/2)**2;return 2*R*Math.asin(Math.sqrt(q));}
  function formatDistance(k){return k<1?`${Math.round(k*1000)} m από εσένα`:`${k.toFixed(k<10?1:0)} km από εσένα`;}
  function markerIcon(category,condition){return L.icon({iconUrl:icons[category]||icons.water_source,iconSize:state.operation?[46,56]:[38,46],iconAnchor:state.operation?[23,54]:[19,44],className:`water-marker ${condition}`});}
  function selectedCategories(){return [...document.querySelectorAll(".dock-filter input:checked")].map(x=>x.value);}
  function visiblePoints(){const q=document.getElementById("searchInput").value.trim().toLocaleLowerCase("el"),cats=selectedCategories();return state.points.filter(p=>cats.includes(p.category)).filter(p=>!q||`${p.name} ${p.notes}`.toLocaleLowerCase("el").includes(q)).filter(p=>!state.nearby||!state.user||distanceKm(state.user.lat,state.user.lng,p.latitude,p.longitude)<=state.radiusKm).filter(p=>!state.operation||p.condition==="available");}
  function render(){state.markers.forEach(m=>map.removeLayer(m));state.markers=[];for(const p of visiblePoints()){const marker=L.marker([p.latitude,p.longitude],{icon:markerIcon(p.category,p.condition),title:p.name}).addTo(map).on("click",()=>openSheet(p));state.markers.push(marker);}document.getElementById("mapCounter").textContent=`${state.markers.length} ${state.markers.length===1?"σημείο":"σημεία"}`;return state.markers;}
  function openSheet(p){const dist=state.user?formatDistance(distanceKm(state.user.lat,state.user.lng,p.latitude,p.longitude)):"";const nav=`https://www.google.com/maps/dir/?api=1&destination=${p.latitude},${p.longitude}`;sheetContent.innerHTML=`<div class="sheet-type"><img src="${icons[p.category]}"><span>${labels[p.category]}</span></div><h2>${esc(p.name)}</h2><span class="status-line ${p.condition}">${conditions[p.condition]}</span>${dist?`<p class="distance">📍 ${dist}</p>`:""}<p class="notes">${esc(p.notes||"Δεν υπάρχουν παρατηρήσεις.")}</p><a class="navigate-button" href="${nav}" target="_blank" rel="noopener">🧭 Πλοήγηση</a>`;sheet.classList.add("open");sheet.setAttribute("aria-hidden","false");}
  function closeSheet(){sheet.classList.remove("open");sheet.setAttribute("aria-hidden","true");}
  function fitMarkers(markers){if(markers.length)map.fitBounds(L.featureGroup(markers).getBounds(),{padding:[45,45],maxZoom:15});}
  function drawUser(pos){state.user={lat:pos.coords.latitude,lng:pos.coords.longitude,accuracy:pos.coords.accuracy};if(state.userMarker)map.removeLayer(state.userMarker);if(state.accuracyCircle)map.removeLayer(state.accuracyCircle);state.userMarker=L.circleMarker([state.user.lat,state.user.lng],{radius:10,weight:4,color:"#fff",fillColor:"#1565c0",fillOpacity:1}).addTo(map).bindTooltip("Η θέση μου");state.accuracyCircle=L.circle([state.user.lat,state.user.lng],{radius:state.user.accuracy,weight:1,fillOpacity:.08,interactive:false}).addTo(map);if(state.operation&&state.follow)map.setView([state.user.lat,state.user.lng],Math.max(map.getZoom(),16));if(state.nearby)render();}
  function startLiveGps(){if(!navigator.geolocation){toast("Η συσκευή δεν υποστηρίζει GPS.","error");return;}if(state.watchId!==null)return;state.watchId=navigator.geolocation.watchPosition(drawUser,e=>toast(({1:"Δεν δόθηκε άδεια GPS.",2:"Η θέση δεν είναι διαθέσιμη.",3:"Η λήψη GPS καθυστέρησε."})[e.code]||"Σφάλμα GPS.","error"),{enableHighAccuracy:true,timeout:20000,maximumAge:3000});toast("Το live GPS ενεργοποιήθηκε.");}
  function stopLiveGps(){if(state.watchId!==null)navigator.geolocation.clearWatch(state.watchId);state.watchId=null;}
  function clearUserLocation(){if(state.userMarker){map.removeLayer(state.userMarker);state.userMarker=null;}if(state.accuracyCircle){map.removeLayer(state.accuracyCircle);state.accuracyCircle=null;}state.user=null;}
  function syncLocateButton(){const active=state.nearby;locateButton.classList.toggle("is-on",active);locateButton.setAttribute("aria-pressed",String(active));const label=locateButton.querySelector(".state-label");if(label)label.textContent=active?"ON":"OFF";}
  function freshPosition(){return new Promise((resolve,reject)=>{if(!navigator.geolocation){reject(new Error("Η συσκευή δεν υποστηρίζει GPS."));return;}navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:25000,maximumAge:0});});}
  async function nearest(){const button=document.getElementById("nearestButton");button.disabled=true;toast("Λήψη νέου στίγματος GPS…");try{const pos=await freshPosition();drawUser(pos);const candidates=state.points.filter(p=>p.condition==="available"&&Number.isFinite(Number(p.latitude))&&Number.isFinite(Number(p.longitude))).map(p=>({...p,distance:distanceKm(pos.coords.latitude,pos.coords.longitude,Number(p.latitude),Number(p.longitude))})).sort((a,b)=>a.distance-b.distance);if(!candidates.length){toast("Δεν υπάρχει λειτουργικό σημείο.","error");return;}const p=candidates[0];map.setView([p.latitude,p.longitude],17);openSheet(p);const accuracy=Math.round(pos.coords.accuracy||0);toast(`Κοντινότερο: ${p.name} · ${formatDistance(p.distance)} · GPS ±${accuracy} m`);}catch(e){const messages={1:"Δεν δόθηκε άδεια GPS.",2:"Η θέση δεν είναι διαθέσιμη.",3:"Η λήψη GPS καθυστέρησε."};toast(messages[e.code]||e.message||"Δεν ήταν δυνατή η λήψη νέου στίγματος.","error");}finally{button.disabled=false;}}
  document.querySelectorAll(".dock-filter input").forEach(i=>i.addEventListener("change",render));
  document.getElementById("searchInput").addEventListener("input",render);document.getElementById("clearSearch").onclick=()=>{document.getElementById("searchInput").value="";render();};document.getElementById("sheetClose").onclick=closeSheet;
  document.getElementById("showAllButton").onclick=()=>{state.nearby=false;document.querySelectorAll(".dock-filter input").forEach(i=>i.checked=true);document.getElementById("searchInput").value="";const m=render();fitMarkers(m);toast("Εμφανίζονται όλα τα σημεία.");};
  locateButton.onclick=()=>{state.nearby=!state.nearby;if(state.nearby){state.radiusKm=4;startLiveGps();toast("Η θέση μου ενεργοποιήθηκε · ακτίνα 4 km.");}else{stopLiveGps();clearUserLocation();toast("Η θέση μου απενεργοποιήθηκε · εμφανίζονται όλα τα επιλεγμένα σημεία.");}syncLocateButton();const markers=render();if(!state.nearby)fitMarkers(markers);};
  syncLocateButton();
  const nearestButton=document.getElementById("nearestButton");if(nearestButton)nearestButton.onclick=nearest;
  document.getElementById("operationButton").onclick=()=>{state.operation=!state.operation;document.body.classList.toggle("operation-mode",state.operation);document.getElementById("operationButton").classList.toggle("active",state.operation);document.getElementById("operationButton").querySelector("span:last-child").textContent=state.operation?"Έξοδος":"Επιχείρηση";if(state.operation){state.nearby=true;startLiveGps();toast("Επιχειρησιακή λειτουργία: μόνο λειτουργικά σημεία σε ακτίνα 4 km.");}else{toast("Κανονική λειτουργία.");}syncLocateButton();render();};
  map.on("dragstart",()=>{if(state.operation)state.follow=false;});map.on("locationfound",drawUser);
  function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
  async function boot(){const badge=document.getElementById("dataBadge");try{const r=await dataService.publicPoints();state.points=r.points;const text={supabase:"Ζωντανά δεδομένα",offline:"Offline δεδομένα",demo:"Δοκιμαστικά δεδομένα"}[r.source]||r.source;badge.textContent=text;badge.className=`connection-badge ${r.source}`;fitMarkers(render());}catch(e){console.error(e);badge.textContent="Σφάλμα δεδομένων";badge.className="connection-badge error";toast(e.message||"Δεν φορτώθηκαν τα σημεία.","error");}}
  boot();
})();
